#!/bin/bash
# scripts by adi1090x

## Get data
TMP_DIR="$HOME/.cache/eww"

## Get status
get_status() {
	if [[ $(playerctl status) == *"Playing"* ]]; then
		echo ""
	else
		echo "奈"
	fi
}

## Get song
get_song() {
	song=`playerctl metadata "xesam:title"`
	if [[ -z "$song" ]]; then
		echo "No Song"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	artist=`playerctl metadata "xesam:artist"`
	if [[ -z "$artist" ]]; then
		echo "No Artist"
	else
		echo "$artist"
	fi	
}

## Get time
get_time() {
	atime=`echo 'print $(($(playerctl position) * 100000000 / $(playerctl metadata "mpris:length")))' | zsh`
        if [[ -z "$atime" ]]; then
                echo "0"
        else
                echo "$atime"
        fi
}

## Get cover
get_cover() {
	cover=`playerctl metadata "mpris:artUrl"`

	# Check if the file has a embbeded album art
	if [[ -z "$cover" ]]; then
		echo "images/music.png"
	else
                id=$(sha1sum <<< "$cover")
                tmp_temp_path="$TMP_DIR/$id.png"
                if [ ! -e "$tmp_temp_path" ]; then
                    curl -sf --create-dirs  "$cover" --output "$tmp_temp_path"
                fi
                echo "$tmp_temp_path" 
        fi
}

## Set position

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	playerctl play-pause
elif [[ "$1" == "--next" ]]; then
	playerctl next
elif [[ "$1" == "--prev" ]]; then
	playerctl previous
fi
