#!/bin/bash

## Files and cmd
# FILE="/tmp/eww_launch.xyz"
EWW="eww -c $HOME/.config/eww/bar"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 

## Launch or close widgets accordingly
# if [[ ! -f "$FILE" ]]; then
#	touch "$FILE"
	${EWW} open-many bar
        sleep 1
#else
#	${EWW} close-all && killall eww
#	rm "$FILE"
#fi


${EWW} update clock_minute="$(date +\%M)" \
     clock_time="$(date +\%I)" \
     clock_date="$(date '+%m/%d')" \
     calendar_day="$(date '+%d')" \
     calendar_month="$(date '+%m')" \
     calendar_year="$(date '+%Y')"
