#!/usr/bin/env bash
rofi \
	-show drun \
	-modi run,drun,ssh \
	-scroll-method 0 \
	-drun-match-fields all \
	-drun-display-format "{name}" \
	-no-drun-show-actions \
	-theme ~/.config/rofi/config/launcher.rasi \
        -icon-theme "Papirus" \
        -show-icons
