#!/usr/bin/bash

# notifications
dunst &

# wallpaper
swww init

if [[ -f "$HOME/.env" ]]; then
    source $HOME/.env
fi

bash $HOME/.scripts/wallpaper/wallpaper.sh &

# eww
source ~/.env 
bash $HOME/.config/eww/launch_bar

# goofy ah protonvpn shit - see https://www.reddit.com/r/ProtonVPN/comments/vgki46/connecting_to_proton_vpn_stuck_in_arch_linux_with/
gnome-keyring-daemon --start
nm-applet &

# enable font managing thing
fcitx5 &

# swayidle
swayidle -w before-sleep '. $HOME/.scripts/lock' &

# kwallet
kwalletd5 &

# gammastep
gammastep &
