#!/usr/bin/bash

export GPG_TTY=$(tty)

# notifications
dunst &

# wallpaper
swww init
swww img ~/.config/hypr/wallpapers/sea.jpg --transition-type center

# waybar
waybar -l trace -c $HOME/.config/waybar/config.json -s $HOME/.config/waybar/style.css &

# redshift
redshift &
