#!/usr/bin/bash

export GPG_TTY=$(tty)

# notifications
dunst &

# wallpaper
swww init
swww img ~/.config/hypr/wallpapers/sea.jpg --transition-type center

# eww
. $HOME/.config/eww/launch_bar

# goofy ah protonvpn shit - see https://www.reddit.com/r/ProtonVPN/comments/vgki46/connecting_to_proton_vpn_stuck_in_arch_linux_with/
gnome-keyring-daemon --start
nm-applet &

# enable font managing thing
fcitx5 &
