#!/usr/bin/env bash

notify-send "Getting list of available Wi-Fi networks..."
# Get a list of available wifi connections and morph it into a nice-looking list
wifi_list=$(nmcli -t --fields "SECURITY,SSID,IN-USE" device wifi list | grep -vE '.+::')

#echo -e "$wifi_list"

currssid=$(echo -e "$wifi_list" | grep "*" | awk -F: '{print $2}')

#echo "$currssid"

# filter list
wifi_list=$(echo -e "$wifi_list" | awk -F: '!seen[$2]++' | awk '{print substr($0, 1, length($0)-2)}' | sed -E "s/WPA[^:]+:/  /g" | sed -E "s/:/  /g")

#echo -e "$wifi_list"

if [[ ! -z $currssid ]]; then
        currindex=$(echo -e "$wifi_list" | grep -En -m 1 ". $currssid" | awk -F ":" '{print $1}' )
fi

#echo -e "$currindex"

# wifi_list=$(nmcli --fields "SECURITY,SSID" device wifi list | sed 1d | sed 's/  */ /g' | sed -E "s/WPA*.?\S/ /g" | sed "s/^--/ /g" | sed "s/  //g" | sed "/--/d")
#
connected=$(nmcli -fields WIFI g)
if [[ "$connected" =~ "enabled" ]]; then
	toggle="睊  Disable Wi-Fi"
elif [[ "$connected" =~ "disabled" ]]; then
	toggle="直  Enable Wi-Fi"
fi

# Use rofi to select wifi network
chosen_network=$(echo -e "$toggle\n$wifi_list" | rofi -dmenu -i -a "$currindex" -selected-row 1 -p "Wi-Fi SSID: " )
# Get name of connection
chosen_id=$(echo "${chosen_network:3}" | xargs)

if [ "$chosen_network" = "" ]; then
	return
elif [ "$chosen_network" = "直  Enable Wi-Fi" ]; then
	nmcli radio wifi on
elif [ "$chosen_network" = "睊  Disable Wi-Fi" ]; then
	nmcli radio wifi off
elif [ "$chosen_id" = "$currssid" ]; then
        nmcli connection down id "$chosen_id"
        return
else
	# Message to show when connection is activated successfully
	success_message="You are now connected to the Wi-Fi network \"$chosen_id\"."
	# Get saved connections
	saved_connections=$(nmcli -g NAME connection)
	check_saved_connections=$(echo "$saved_connections" | grep -w "$chosen_id")
	if [[ $check_saved_connections = "$chosen_id" ]]; then
		nmcli connection up id "$chosen_id" | grep "successfully" || wifi_password=$(rofi -dmenu -p "Password: " ) && nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && notify-send "Connection Established" "$success_message"
	else
		if [[ "$chosen_network" =~ "" ]]; then
			wifi_password=$(rofi -dmenu -p "Password: " )
		fi
		nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && notify-send "$success_message"
	fi
fi
