#!/usr/bin/bash
swaylockd \
--screenshots \
--indicator \
--clock \
--inside-wrong-color f38ba8  \
--ring-wrong-color 11111b  \
--inside-clear-color a6e3a1 \
--ring-clear-color 11111b \
--inside-ver-color 74c7ec \
--ring-ver-color 11111b \
--text-color  89dceb \
--indicator-radius 80 \
--indicator-thickness 5 \
--effect-blur 10x15 \
--effect-vignette 0.3:0.3 \
--ring-color 11111b \
--key-hl-color 89dceb \
--line-color 313244 \
--inside-color 0011111b \
--separator-color 00000000 \
--fade-in 0.4 &

